id:
  generationStrategy: uuid
validator:
  assertType: true
types:
  PostalAddress:
    properties:
      addressCountry: { range: "Text" }
      addressLocality: ~
      postalCode: ~
      streetAddress: ~
  Place:
    properties:
      address: { range: "PostalAddress" }
      hasMap: { range: "URL" }
      latitude: { range: "Number" }
      longitude: { range: "Number" }
      maximumAttendeeCapacity: ~
  Organization:
    properties:
      name: ~
      description: ~
      disambiguatingDescription: ~
      image: ~
      url: ~
      location: { range: "Place" }
      email: ~
      employees:
        cardinality: "(0..*)"
        range: "Person"
  Person:
    properties:
      additionalName: ~
      familyName: ~
      givenName: ~
      honorificPrefix: ~
      description: ~
      disambiguatingDescription: ~
      image: ~
      url: ~
      memberOf: { range: "Organization" }
